
export default {

  LOG_IN_FULFILLED: 'LOG_IN_SUCCESSFUL',
  LOG_IN_REJECTED: 'LOG_IN_REJECTED',
  LOG_IN_PENDING: 'LOG_IN_PENDING',

  CHECK_LOGIN: 'CHECK_LOGIN',

  LOG_OUT_FULFILLED: 'LOG_OUT_SUCCESSFUL',
  LOG_OUT_REJECTED: 'LOG_OUT_REJECTED',
  LOG_OUT_PENDING: 'LOG_OUT_PENDING',

  FETCH_PROFILES_PENDING: 'FETCH_PROFILES_PENDING',
  FETCH_PROFILES_FULFILLED: 'FETCH_PROFILES_FULFILLED',
  FETCH_PROFILES_REJECTED: 'FETCH_PROFILES_REJECTED',

  CREATE_PROFILE_PENDING: 'CREATE_PROFILE_PENDING',
  CREATE_PROFILE_FULFILLED: 'CREATE_PROFILE_FULFILLED',
  CREATE_PROFILE_REJECTED: 'CREATE_PROFILE_REJECTED',

  DELETE_PROFILE_PENDING: 'DELETE_PROFILE_PENDING',
  DELETE_PROFILE_FULFILLED: 'DELETE_PROFILE_FULFILLED',
  DELETE_PROFILE_REJECTED: 'DELETE_PROFILE_REJECTED',
};
